name: compile and unit test on native arch
on:
  push:
    branches:
      - master
      - queue
      - tip
      - next
      - factory
      - sles*
  pull_request:

jobs:
  stable:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-buster
          - debian-jessie
          - debian-bullseye
          - fedora-36
          - opensuse-leap
    container: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build and test
        if: ${{ matrix.os != 'jessie' }}
        run: make test
      - name: build and test (jessie)
        # On jessie, we use libreadline 5 (no licensing issue)
        if: ${{ matrix.os == 'jessie' }}
        run: make  -j -Orecurse READLINE=libreadline test
      - name: clean
        run: make clean
      - name: clang
        if: ${{ matrix.os != 'jessie' }}
        env:
          CC: clang
        run: make -j -Orecurse test
      - name: clang (jessie)
        if: ${{ matrix.os == 'jessie' }}
        env:
          CC: clang
        run: make READLINE=libreadline test
