name: compile and unit test on Leap
on:
  push:
    branches:
      - sles*
      - factory
      - next

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: ['leap15.2', 'leap15.4']
        # We have -arm too (for armv7l)
        # But tests fail with qemu-user (readdir() returns -EOVERFLOW), see
        # https://gitlab.com/qemu-project/qemu/-/issues/263
        # https://sourceware.org/bugzilla/show_bug.cgi?id=23960
        # Attempts to fix this with -D_FILE_OFFSET_BITS=64 failed, too
        # this means replacing cmocka wrappers like __wrap_lseek() with
        # __wrap_lseek64()

        arch: ['', '-ppc64le', '-arm64', '-s390x']
        include:
          - os: 'leap15.3'
            arch: '-s390x'
        exclude:
          - os: 'leap15.2'
            arch: '-s390x'
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: enable foreign arch
        run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: build and run unit tests
        # Github actions doesn't support referencing docker images with
        # context variables. Workaround: use mosteo-actions/docker-run action
        # See https://github.community/t/expressions-in-docker-uri/16271
        uses: mosteo-actions/docker-run@v1
        with:
          image: mwilck/multipath-build-${{ matrix.os }}${{ matrix.arch }}
          command: test

